# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
# https://raw.githubusercontent.com/PSModule

changelog:
  exclude:
    labels:
      - Category-Tests ✅
      - Category-Build 🚀
  categories:
    - title: 🌟 Breaking Changes
      labels:
        - Major
        - Breaking
    - title: 🚀 New Features
      labels:
        - Minor
        - Feature
    - title: Other Changes
      labels:
        - '*'
