# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
# https://raw.githubusercontent.com/PSModule

changelog:
  exclude:
    labels:
      - Category-Tests ✅
      - Category-Build 🚀
      - ignore-for-release
  categories:
    - title: 🌟 Breaking Changes
      labels:
        - Breaking 🌟
    - title: 🎉 New Features
      labels:
        - Issue-Feature 🎉
    - title: ✨ Enhancements
      labels:
        - Issue-Enhancement ✨
    - title: 🐛 Bug Fixes
      labels:
        - Issue-Bug 🐛
    - title: ♻️ Refactored
      labels:
        - Refactor ♻️
    - title: Security Fixes 🔒
      labels:
        - Security 🔒
    - title: Other Changes
      labels:
        - '*'
